// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type NetworkInitParameters struct {

	// Automatically create an IPv4 Subnet on the network. Can be true (default) or false.
	AutoCreateIPv4Subnet *bool `json:"autoCreateIpv4Subnet,omitempty" tf:"auto_create_ipv4_subnet,omitempty"`

	// You can specify the MTU size for the network, defaults to 9000.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// Name of the network.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The slug of the zone in which the new network will be created. Options include lpg1 and rma1.
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type NetworkObservation struct {

	// Automatically create an IPv4 Subnet on the network. Can be true (default) or false.
	AutoCreateIPv4Subnet *bool `json:"autoCreateIpv4Subnet,omitempty" tf:"auto_create_ipv4_subnet,omitempty"`

	// The cloudscale.ch API URL of the current network.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// You can specify the MTU size for the network, defaults to 9000.
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// Name of the network.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A list of subnet objects that are used in this network. Each subnet object has the following attributes:
	Subnets []SubnetsObservation `json:"subnets,omitempty" tf:"subnets,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The slug of the zone in which the new network will be created. Options include lpg1 and rma1.
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type NetworkParameters struct {

	// Automatically create an IPv4 Subnet on the network. Can be true (default) or false.
	// +kubebuilder:validation:Optional
	AutoCreateIPv4Subnet *bool `json:"autoCreateIpv4Subnet,omitempty" tf:"auto_create_ipv4_subnet,omitempty"`

	// You can specify the MTU size for the network, defaults to 9000.
	// +kubebuilder:validation:Optional
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// Name of the network.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The slug of the zone in which the new network will be created. Options include lpg1 and rma1.
	// +kubebuilder:validation:Optional
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type SubnetsInitParameters struct {
}

type SubnetsObservation struct {

	// The CIDR notation of the subnet.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// The cloudscale.ch API URL of the current network.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// The UUID of this subnet.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type SubnetsParameters struct {
}

// NetworkSpec defines the desired state of Network
type NetworkSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkInitParameters `json:"initProvider,omitempty"`
}

// NetworkStatus defines the observed state of Network.
type NetworkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Network is the Schema for the Networks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudscale}
type Network struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   NetworkSpec   `json:"spec"`
	Status NetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkList contains a list of Networks
type NetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Network `json:"items"`
}

// Repository type metadata.
var (
	Network_Kind             = "Network"
	Network_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Network_Kind}.String()
	Network_KindAPIVersion   = Network_Kind + "." + CRDGroupVersion.String()
	Network_GroupVersionKind = CRDGroupVersion.WithKind(Network_Kind)
)

func init() {
	SchemeBuilder.Register(&Network{}, &NetworkList{})
}
