// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AddressesInitParameters struct {

	// An IP address that has been assigned to this server.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The UUID of the subnet this address should be part of. Must be compatible with network_uuid if both are specified.
	// +crossplane:generate:reference:type=github.com/splattner/provider-cloudscale/apis/cluster/cloudscale/v1alpha1.Subnet
	SubnetUUID *string `json:"subnetUuid,omitempty" tf:"subnet_uuid,omitempty"`

	// Reference to a Subnet in cloudscale to populate subnetUuid.
	// +kubebuilder:validation:Optional
	SubnetUUIDRef *v1.Reference `json:"subnetUuidRef,omitempty" tf:"-"`

	// Selector for a Subnet in cloudscale to populate subnetUuid.
	// +kubebuilder:validation:Optional
	SubnetUUIDSelector *v1.Selector `json:"subnetUuidSelector,omitempty" tf:"-"`
}

type AddressesObservation struct {

	// An IP address that has been assigned to this server.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// An IPv4 or IPv6 address that represents the default gateway for this interface.
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// The prefix length for this IP address, typically 24 for IPv4 and 128 for IPv6.
	PrefixLength *float64 `json:"prefixLength,omitempty" tf:"prefix_length,omitempty"`

	// The PTR record (reverse DNS pointer) for this IP address. If you use an FQDN as your server name it will automatically be used here.
	ReversePtr *string `json:"reversePtr,omitempty" tf:"reverse_ptr,omitempty"`

	// The cidr of the subnet the address is part of.
	SubnetCidr *string `json:"subnetCidr,omitempty" tf:"subnet_cidr,omitempty"`

	// The cloudscale.ch API URL of the subnet the address is part of.
	SubnetHref *string `json:"subnetHref,omitempty" tf:"subnet_href,omitempty"`

	// The UUID of the subnet this address should be part of. Must be compatible with network_uuid if both are specified.
	SubnetUUID *string `json:"subnetUuid,omitempty" tf:"subnet_uuid,omitempty"`

	// The IP version, either 4 or 6.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type AddressesParameters struct {

	// An IP address that has been assigned to this server.
	// +kubebuilder:validation:Optional
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// The UUID of the subnet this address should be part of. Must be compatible with network_uuid if both are specified.
	// +crossplane:generate:reference:type=github.com/splattner/provider-cloudscale/apis/cluster/cloudscale/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	SubnetUUID *string `json:"subnetUuid,omitempty" tf:"subnet_uuid,omitempty"`

	// Reference to a Subnet in cloudscale to populate subnetUuid.
	// +kubebuilder:validation:Optional
	SubnetUUIDRef *v1.Reference `json:"subnetUuidRef,omitempty" tf:"-"`

	// Selector for a Subnet in cloudscale to populate subnetUuid.
	// +kubebuilder:validation:Optional
	SubnetUUIDSelector *v1.Selector `json:"subnetUuidSelector,omitempty" tf:"-"`
}

type InterfacesInitParameters struct {

	// A list of address objects:
	Addresses []AddressesInitParameters `json:"addresses,omitempty" tf:"addresses,omitempty"`

	// The UUID of the private network this interface should be attached to. Must be compatible with subnet_uuid if both are specified.
	// +crossplane:generate:reference:type=github.com/splattner/provider-cloudscale/apis/cluster/cloudscale/v1alpha1.Network
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in cloudscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.Reference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in cloudscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.Selector `json:"networkUuidSelector,omitempty" tf:"-"`

	// You need to set this to true if no address should be configured, e.g. if you want to attach to a network without a subnet.
	NoAddress *bool `json:"noAddress,omitempty" tf:"no_address,omitempty"`

	// The type of the interface. Can be public or private.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type InterfacesObservation struct {

	// A list of address objects:
	Addresses []AddressesObservation `json:"addresses,omitempty" tf:"addresses,omitempty"`

	// The cloudscale.ch API URL of the network the interface is attached to.
	NetworkHref *string `json:"networkHref,omitempty" tf:"network_href,omitempty"`

	// The name of the network the interface is attached to.
	NetworkName *string `json:"networkName,omitempty" tf:"network_name,omitempty"`

	// The UUID of the private network this interface should be attached to. Must be compatible with subnet_uuid if both are specified.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// You need to set this to true if no address should be configured, e.g. if you want to attach to a network without a subnet.
	NoAddress *bool `json:"noAddress,omitempty" tf:"no_address,omitempty"`

	// The type of the interface. Can be public or private.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type InterfacesParameters struct {

	// A list of address objects:
	// +kubebuilder:validation:Optional
	Addresses []AddressesParameters `json:"addresses,omitempty" tf:"addresses,omitempty"`

	// The UUID of the private network this interface should be attached to. Must be compatible with subnet_uuid if both are specified.
	// +crossplane:generate:reference:type=github.com/splattner/provider-cloudscale/apis/cluster/cloudscale/v1alpha1.Network
	// +kubebuilder:validation:Optional
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in cloudscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.Reference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in cloudscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.Selector `json:"networkUuidSelector,omitempty" tf:"-"`

	// You need to set this to true if no address should be configured, e.g. if you want to attach to a network without a subnet.
	// +kubebuilder:validation:Optional
	NoAddress *bool `json:"noAddress,omitempty" tf:"no_address,omitempty"`

	// The type of the interface. Can be public or private.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type ServerGroupsInitParameters struct {
}

type ServerGroupsObservation struct {

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// Name of the new server. The name has to be a valid host name or a fully qualified domain name (FQDN).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of this server.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ServerGroupsParameters struct {
}

type ServerInitParameters struct {

	// If you try to update a property that requires stopping the instance without setting this field, the update will fail.
	AllowStoppingForUpdate *bool `json:"allowStoppingForUpdate,omitempty" tf:"allow_stopping_for_update,omitempty"`

	// The size in GB of the bulk storage volume of the new server. If this parameter is not specified, no bulk storage volume will be attached to the server. Valid values are multiples of 100.
	BulkVolumeSizeGb *float64 `json:"bulkVolumeSizeGb,omitempty" tf:"bulk_volume_size_gb,omitempty"`

	// The slug (name) of the flavor to use for the new server. Possible values can be found in our API documentation.
	// Note: If you want to update this value after initial creation, you must set allow_stopping_for_update to true.
	FlavorSlug *string `json:"flavorSlug,omitempty" tf:"flavor_slug,omitempty"`

	// The slug (name) of the image (or custom image) to use for the new server. Possible values can be found in our API documentation.
	ImageSlug *string `json:"imageSlug,omitempty" tf:"image_slug,omitempty"`

	// The UUID of the custom image to use for the new server. Note: This is the recommended approach for custom images.
	ImageUUID *string `json:"imageUuid,omitempty" tf:"image_uuid,omitempty"`

	// A list of interface configuration objects (see example). Each interface object has the following attributes:
	Interfaces []InterfacesInitParameters `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// Name of the new server. The name has to be a valid host name or a fully qualified domain name (FQDN).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The password of the default user of the new server. When omitted, no password will be set.
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// A list of SSH public keys. Use the full content of your *.pub file here.
	// +listType=set
	SSHKeys []*string `json:"sshKeys,omitempty" tf:"ssh_keys,omitempty"`

	// A list of server group UUIDs to which the server should be added. Default to an empty list.
	// +listType=set
	ServerGroupIds []*string `json:"serverGroupIds,omitempty" tf:"server_group_ids,omitempty"`

	// If set to true, do not wait until SSH host keys become available.
	SkipWaitingForSSHHostKeys *bool `json:"skipWaitingForSshHostKeys,omitempty" tf:"skip_waiting_for_ssh_host_keys,omitempty"`

	// The desired state of a server. Can be running (default) or stopped.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Enable/disable IPv6 on the public network interface of the new server. Can be true (default) or false.
	UseIPv6 *bool `json:"useIpv6,omitempty" tf:"use_ipv6,omitempty"`

	// Attach the default private network interface to the new server. Can be true or false (default). Use interfaces option for advanced setups.
	UsePrivateNetwork *bool `json:"usePrivateNetwork,omitempty" tf:"use_private_network,omitempty"`

	// Attach the public network interface to the new server. Can be true (default) or false. Use interfaces option for advanced setups.
	UsePublicNetwork *bool `json:"usePublicNetwork,omitempty" tf:"use_public_network,omitempty"`

	// User data (custom cloud-config settings) to use for the new server. Needs to be valid YAML. A default configuration will be used if this parameter is not specified or set to null. Use only if you are an advanced user with knowledge of cloud-config and cloud-init.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// The size in GB of the SSD root volume of the new server. If this parameter is not specified, the value will be set to 10. The minimum value is 10.
	VolumeSizeGb *float64 `json:"volumeSizeGb,omitempty" tf:"volume_size_gb,omitempty"`

	// The slug of the zone in which the new server will be created. Options include lpg1 and rma1.
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type ServerObservation struct {

	// If you try to update a property that requires stopping the instance without setting this field, the update will fail.
	AllowStoppingForUpdate *bool `json:"allowStoppingForUpdate,omitempty" tf:"allow_stopping_for_update,omitempty"`

	// The size in GB of the bulk storage volume of the new server. If this parameter is not specified, no bulk storage volume will be attached to the server. Valid values are multiples of 100.
	BulkVolumeSizeGb *float64 `json:"bulkVolumeSizeGb,omitempty" tf:"bulk_volume_size_gb,omitempty"`

	// The slug (name) of the flavor to use for the new server. Possible values can be found in our API documentation.
	// Note: If you want to update this value after initial creation, you must set allow_stopping_for_update to true.
	FlavorSlug *string `json:"flavorSlug,omitempty" tf:"flavor_slug,omitempty"`

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	// The UUID of this server.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The slug (name) of the image (or custom image) to use for the new server. Possible values can be found in our API documentation.
	ImageSlug *string `json:"imageSlug,omitempty" tf:"image_slug,omitempty"`

	// The UUID of the custom image to use for the new server. Note: This is the recommended approach for custom images.
	ImageUUID *string `json:"imageUuid,omitempty" tf:"image_uuid,omitempty"`

	// A list of interface configuration objects (see example). Each interface object has the following attributes:
	Interfaces []InterfacesObservation `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// Name of the new server. The name has to be a valid host name or a fully qualified domain name (FQDN).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The first private IPv4 address of this server. The returned IP address may be "" if the server does not have private networking enabled.
	PrivateIPv4Address *string `json:"privateIpv4Address,omitempty" tf:"private_ipv4_address,omitempty"`

	// The first public IPv4 address of this server. The returned IP address may be "" if the server does not have a public IPv4.
	PublicIPv4Address *string `json:"publicIpv4Address,omitempty" tf:"public_ipv4_address,omitempty"`

	// The first public IPv6 address of this server. The returned IP address may be "" if the server does not have a public IPv6.
	PublicIPv6Address *string `json:"publicIpv6Address,omitempty" tf:"public_ipv6_address,omitempty"`

	// A list of SSH host key fingerprints (strings) of this server.
	SSHFingerprints []*string `json:"sshFingerprints,omitempty" tf:"ssh_fingerprints,omitempty"`

	// A list of SSH host keys (strings) of this server.
	SSHHostKeys []*string `json:"sshHostKeys,omitempty" tf:"ssh_host_keys,omitempty"`

	// A list of SSH public keys. Use the full content of your *.pub file here.
	// +listType=set
	SSHKeys []*string `json:"sshKeys,omitempty" tf:"ssh_keys,omitempty"`

	// A list of server group UUIDs to which the server should be added. Default to an empty list.
	// +listType=set
	ServerGroupIds []*string `json:"serverGroupIds,omitempty" tf:"server_group_ids,omitempty"`

	ServerGroups []ServerGroupsObservation `json:"serverGroups,omitempty" tf:"server_groups,omitempty"`

	// If set to true, do not wait until SSH host keys become available.
	SkipWaitingForSSHHostKeys *bool `json:"skipWaitingForSshHostKeys,omitempty" tf:"skip_waiting_for_ssh_host_keys,omitempty"`

	// The desired state of a server. Can be running (default) or stopped.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Enable/disable IPv6 on the public network interface of the new server. Can be true (default) or false.
	UseIPv6 *bool `json:"useIpv6,omitempty" tf:"use_ipv6,omitempty"`

	// Attach the default private network interface to the new server. Can be true or false (default). Use interfaces option for advanced setups.
	UsePrivateNetwork *bool `json:"usePrivateNetwork,omitempty" tf:"use_private_network,omitempty"`

	// Attach the public network interface to the new server. Can be true (default) or false. Use interfaces option for advanced setups.
	UsePublicNetwork *bool `json:"usePublicNetwork,omitempty" tf:"use_public_network,omitempty"`

	// User data (custom cloud-config settings) to use for the new server. Needs to be valid YAML. A default configuration will be used if this parameter is not specified or set to null. Use only if you are an advanced user with knowledge of cloud-config and cloud-init.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// The size in GB of the SSD root volume of the new server. If this parameter is not specified, the value will be set to 10. The minimum value is 10.
	VolumeSizeGb *float64 `json:"volumeSizeGb,omitempty" tf:"volume_size_gb,omitempty"`

	// A list of volume objects attached to this server. Each volume object has three attributes:
	Volumes []VolumesObservation `json:"volumes,omitempty" tf:"volumes,omitempty"`

	// The slug of the zone in which the new server will be created. Options include lpg1 and rma1.
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type ServerParameters struct {

	// If you try to update a property that requires stopping the instance without setting this field, the update will fail.
	// +kubebuilder:validation:Optional
	AllowStoppingForUpdate *bool `json:"allowStoppingForUpdate,omitempty" tf:"allow_stopping_for_update,omitempty"`

	// The size in GB of the bulk storage volume of the new server. If this parameter is not specified, no bulk storage volume will be attached to the server. Valid values are multiples of 100.
	// +kubebuilder:validation:Optional
	BulkVolumeSizeGb *float64 `json:"bulkVolumeSizeGb,omitempty" tf:"bulk_volume_size_gb,omitempty"`

	// The slug (name) of the flavor to use for the new server. Possible values can be found in our API documentation.
	// Note: If you want to update this value after initial creation, you must set allow_stopping_for_update to true.
	// +kubebuilder:validation:Optional
	FlavorSlug *string `json:"flavorSlug,omitempty" tf:"flavor_slug,omitempty"`

	// The slug (name) of the image (or custom image) to use for the new server. Possible values can be found in our API documentation.
	// +kubebuilder:validation:Optional
	ImageSlug *string `json:"imageSlug,omitempty" tf:"image_slug,omitempty"`

	// The UUID of the custom image to use for the new server. Note: This is the recommended approach for custom images.
	// +kubebuilder:validation:Optional
	ImageUUID *string `json:"imageUuid,omitempty" tf:"image_uuid,omitempty"`

	// A list of interface configuration objects (see example). Each interface object has the following attributes:
	// +kubebuilder:validation:Optional
	Interfaces []InterfacesParameters `json:"interfaces,omitempty" tf:"interfaces,omitempty"`

	// Name of the new server. The name has to be a valid host name or a fully qualified domain name (FQDN).
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The password of the default user of the new server. When omitted, no password will be set.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// A list of SSH public keys. Use the full content of your *.pub file here.
	// +kubebuilder:validation:Optional
	// +listType=set
	SSHKeys []*string `json:"sshKeys,omitempty" tf:"ssh_keys,omitempty"`

	// A list of server group UUIDs to which the server should be added. Default to an empty list.
	// +kubebuilder:validation:Optional
	// +listType=set
	ServerGroupIds []*string `json:"serverGroupIds,omitempty" tf:"server_group_ids,omitempty"`

	// If set to true, do not wait until SSH host keys become available.
	// +kubebuilder:validation:Optional
	SkipWaitingForSSHHostKeys *bool `json:"skipWaitingForSshHostKeys,omitempty" tf:"skip_waiting_for_ssh_host_keys,omitempty"`

	// The desired state of a server. Can be running (default) or stopped.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Enable/disable IPv6 on the public network interface of the new server. Can be true (default) or false.
	// +kubebuilder:validation:Optional
	UseIPv6 *bool `json:"useIpv6,omitempty" tf:"use_ipv6,omitempty"`

	// Attach the default private network interface to the new server. Can be true or false (default). Use interfaces option for advanced setups.
	// +kubebuilder:validation:Optional
	UsePrivateNetwork *bool `json:"usePrivateNetwork,omitempty" tf:"use_private_network,omitempty"`

	// Attach the public network interface to the new server. Can be true (default) or false. Use interfaces option for advanced setups.
	// +kubebuilder:validation:Optional
	UsePublicNetwork *bool `json:"usePublicNetwork,omitempty" tf:"use_public_network,omitempty"`

	// User data (custom cloud-config settings) to use for the new server. Needs to be valid YAML. A default configuration will be used if this parameter is not specified or set to null. Use only if you are an advanced user with knowledge of cloud-config and cloud-init.
	// +kubebuilder:validation:Optional
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// The size in GB of the SSD root volume of the new server. If this parameter is not specified, the value will be set to 10. The minimum value is 10.
	// +kubebuilder:validation:Optional
	VolumeSizeGb *float64 `json:"volumeSizeGb,omitempty" tf:"volume_size_gb,omitempty"`

	// The slug of the zone in which the new server will be created. Options include lpg1 and rma1.
	// +kubebuilder:validation:Optional
	ZoneSlug *string `json:"zoneSlug,omitempty" tf:"zone_slug,omitempty"`
}

type VolumesInitParameters struct {
}

type VolumesObservation struct {

	// The path (string) to the volume on your server (e.g. /dev/vda)
	DevicePath *string `json:"devicePath,omitempty" tf:"device_path,omitempty"`

	// The size (int) of the volume in GB. Typically matches volume_size_gb or bulk_volume_size_gb.
	SizeGb *float64 `json:"sizeGb,omitempty" tf:"size_gb,omitempty"`

	// The type of the interface. Can be public or private.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The UUID of this server.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type VolumesParameters struct {
}

// ServerSpec defines the desired state of Server
type ServerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServerInitParameters `json:"initProvider,omitempty"`
}

// ServerStatus defines the observed state of Server.
type ServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Server is the Schema for the Servers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudscale}
type Server struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.flavorSlug) || (has(self.initProvider) && has(self.initProvider.flavorSlug))",message="spec.forProvider.flavorSlug is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ServerSpec   `json:"spec"`
	Status ServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerList contains a list of Servers
type ServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Server `json:"items"`
}

// Repository type metadata.
var (
	Server_Kind             = "Server"
	Server_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Server_Kind}.String()
	Server_KindAPIVersion   = Server_Kind + "." + CRDGroupVersion.String()
	Server_GroupVersionKind = CRDGroupVersion.WithKind(Server_Kind)
)

func init() {
	SchemeBuilder.Register(&Server{}, &ServerList{})
}
