// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type KeysInitParameters struct {
}

type KeysObservation struct {

	// The S3 access key of the Objects User.
	AccessKey *string `json:"accessKey,omitempty" tf:"access_key,omitempty"`

	// The S3 secret key of the Objects User.
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`
}

type KeysParameters struct {
}

type ObjectsUserInitParameters struct {

	// The display name of the Objects User.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type ObjectsUserObservation struct {

	// The display name of the Objects User.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The cloudscale.ch API URL of the current resource.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The unique identifier of the Objects User.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type ObjectsUserParameters struct {

	// The display name of the Objects User.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// ObjectsUserSpec defines the desired state of ObjectsUser
type ObjectsUserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ObjectsUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ObjectsUserInitParameters `json:"initProvider,omitempty"`
}

// ObjectsUserStatus defines the observed state of ObjectsUser.
type ObjectsUserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ObjectsUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ObjectsUser is the Schema for the ObjectsUsers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudscale}
type ObjectsUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   ObjectsUserSpec   `json:"spec"`
	Status ObjectsUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ObjectsUserList contains a list of ObjectsUsers
type ObjectsUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ObjectsUser `json:"items"`
}

// Repository type metadata.
var (
	ObjectsUser_Kind             = "ObjectsUser"
	ObjectsUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ObjectsUser_Kind}.String()
	ObjectsUser_KindAPIVersion   = ObjectsUser_Kind + "." + CRDGroupVersion.String()
	ObjectsUser_GroupVersionKind = CRDGroupVersion.WithKind(ObjectsUser_Kind)
)

func init() {
	SchemeBuilder.Register(&ObjectsUser{}, &ObjectsUserList{})
}
