// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SubnetInitParameters struct {

	// The address range in CIDR notation. Must be at least /24.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// A list of DNS resolver IP addresses, that act as DNS servers. If not defined, default DNS servers are used. Do not explicitly set to an empty list (dns_servers = []), use disable_dns_servers instead.
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// If set to true, no DNS servers are set. Can not be used together with dns_servers.
	DisableDNSServers *bool `json:"disableDnsServers,omitempty" tf:"disable_dns_servers,omitempty"`

	// The gateway address of the subnet.
	GatewayAddress *string `json:"gatewayAddress,omitempty" tf:"gateway_address,omitempty"`

	// The network of the subnet.
	// +crossplane:generate:reference:type=github.com/splattner/provider-cloudscale/apis/cluster/cloudscale/v1alpha1.Network
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in cloudscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.NamespacedReference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in cloudscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.NamespacedSelector `json:"networkUuidSelector,omitempty" tf:"-"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type SubnetObservation struct {

	// The address range in CIDR notation. Must be at least /24.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// A list of DNS resolver IP addresses, that act as DNS servers. If not defined, default DNS servers are used. Do not explicitly set to an empty list (dns_servers = []), use disable_dns_servers instead.
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// If set to true, no DNS servers are set. Can not be used together with dns_servers.
	DisableDNSServers *bool `json:"disableDnsServers,omitempty" tf:"disable_dns_servers,omitempty"`

	// The gateway address of the subnet.
	GatewayAddress *string `json:"gatewayAddress,omitempty" tf:"gateway_address,omitempty"`

	// The cloudscale.ch API URL of the current subnet.
	Href *string `json:"href,omitempty" tf:"href,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The cloudscale.ch API URL of the subnet's network.
	NetworkHref *string `json:"networkHref,omitempty" tf:"network_href,omitempty"`

	// The network name of the subnet.
	NetworkName *string `json:"networkName,omitempty" tf:"network_name,omitempty"`

	// The network of the subnet.
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type SubnetParameters struct {

	// The address range in CIDR notation. Must be at least /24.
	// +kubebuilder:validation:Optional
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// A list of DNS resolver IP addresses, that act as DNS servers. If not defined, default DNS servers are used. Do not explicitly set to an empty list (dns_servers = []), use disable_dns_servers instead.
	// +kubebuilder:validation:Optional
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// If set to true, no DNS servers are set. Can not be used together with dns_servers.
	// +kubebuilder:validation:Optional
	DisableDNSServers *bool `json:"disableDnsServers,omitempty" tf:"disable_dns_servers,omitempty"`

	// The gateway address of the subnet.
	// +kubebuilder:validation:Optional
	GatewayAddress *string `json:"gatewayAddress,omitempty" tf:"gateway_address,omitempty"`

	// The network of the subnet.
	// +crossplane:generate:reference:type=github.com/splattner/provider-cloudscale/apis/cluster/cloudscale/v1alpha1.Network
	// +kubebuilder:validation:Optional
	NetworkUUID *string `json:"networkUuid,omitempty" tf:"network_uuid,omitempty"`

	// Reference to a Network in cloudscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDRef *v1.NamespacedReference `json:"networkUuidRef,omitempty" tf:"-"`

	// Selector for a Network in cloudscale to populate networkUuid.
	// +kubebuilder:validation:Optional
	NetworkUUIDSelector *v1.NamespacedSelector `json:"networkUuidSelector,omitempty" tf:"-"`

	// Tags allow you to assign custom metadata to resources:
	// tags = {
	// foo = "bar"
	// }
	//
	// Tags are always strings (both keys and values).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// SubnetSpec defines the desired state of Subnet
type SubnetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SubnetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubnetInitParameters `json:"initProvider,omitempty"`
}

// SubnetStatus defines the observed state of Subnet.
type SubnetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubnetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Subnet is the Schema for the Subnets API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudscale}
type Subnet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cidr) || (has(self.initProvider) && has(self.initProvider.cidr))",message="spec.forProvider.cidr is a required parameter"
	Spec   SubnetSpec   `json:"spec"`
	Status SubnetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubnetList contains a list of Subnets
type SubnetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Subnet `json:"items"`
}

// Repository type metadata.
var (
	Subnet_Kind             = "Subnet"
	Subnet_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Subnet_Kind}.String()
	Subnet_KindAPIVersion   = Subnet_Kind + "." + CRDGroupVersion.String()
	Subnet_GroupVersionKind = CRDGroupVersion.WithKind(Subnet_Kind)
)

func init() {
	SchemeBuilder.Register(&Subnet{}, &SubnetList{})
}
